### ISSUE TITLE
Conflict with "ShortCode Core" plugin

### ISSUE THREAD

**Issue by vincowl** [Birssan/grav-plugin-about-me#10]
If ShortCode core plugin is activated, an empty shadowed box is displayed instead of the aboutme content.

**Comment by seb-vial** [comment]
For some reason, twig vars are not set in that case or maybe overwritten I don't know.
I've changed `aboutme.php` locally and handled the `onTwigPageVariables` event to set twig variables "again" and it works. The question is, why does it work without the event subscription when the Shortcode plugin is not enabled...
I'll commit my changes and make a new release soon.

**Comment by vincowl** [comment]
Thanks !
