### ISSUE TITLE
Display troubles with Helium theme

### ISSUE THREAD

**Issue by vincowl** [Birssan/grav-plugin-about-me#11]
When using Helium theme and aboutMe plugin, the aboutme's description is display with `<p>...</p>` tags. Don't know if it's relative to aboutme or gantry5 plugin upon which Helium theme is built. Doesn't happen with Antimatter theme...
![aboutme helium](https://user-images.githubusercontent.com/16786457/31615278-5a7fc90a-b289-11e7-8df8-4dafab2a7059.png)

**Comment by seb-vial** [comment]
After a quick search in the gantry issue tracker, I could find some similar issues, it's fixable by adding a `|raw` filter for the description. Fortunately, it doesn't break the plugin when using the filter with other themes. I'll commit that quickly.

**Comment by vincowl** [comment]
Thanks ! It works like a charm now !
