### ISSUE TITLE
Empty 'Title' not possible

### ISSUE THREAD

**Issue by metbril** [Birssan/grav-plugin-about-me#13]
I don't like a job title in the about me page of my personal website. So I'd like to leave it empty. However, saving an empty value in the admin panel will show the plugin default for Santa. 

A workaround is to save a space character which shows up empty. But this renders a `<h3>` section with the space.

Since reverting to the plugin default is standard Grav behaviour, I think the only option to really suppress the job title would be to create a toggle for this. If you allow a PR for this, I will submit one.

**Comment by seb-vial** [comment]
In deed I suppose a toggle would be the right option here.
If you have time to make a PR, that's great, I'll merge it whenever I can, thank you.

**Comment by metbril** [comment]
I will submit a PR in the coming day(s). You could wait with a new release and include this as well.

**Comment by seb-vial** [comment]
Thank you.
My thought exactly ;)

**Comment by metbril** [comment]
That was not too difficult. I just love Grav.
