### ISSUE TITLE
Google+ discontinued

### ISSUE THREAD

**Issue by metbril** [Birssan/grav-plugin-about-me#16]
Google+ will be discontinued for consumers soon.

https://www.blog.google/technology/safety-security/project-strobe/

I think any reference in the plugin can be removed. If required, people can alway add it manually like any other profile.

**Comment by seb-vial** [comment]
Yes, that's probably a good idea. Just wondering if it should be done now or when GPlus is officially shutdown

**Comment by gbschenkel** [comment]
Hi, Google+ is official out of service! I like to inform some icons from Font Awesome like [mastodon](https://fontawesome.com/icons/mastodon?style=brands) and [telegram-plane](https://fontawesome.com/icons/telegram-plane?style=brands) doesn't show up on About Me, [gitlab](https://fontawesome.com/icons/gitlab?style=brands) show but with a wrong icon.
I try to find the link to the icons source but I couldn't. Is it pointing to the last version of the branding icons?

**Comment by gbschenkel** [comment]
@Birssan the commit worked! 
Could I made a request to insert a spinbox to set the pixel size for the icons like Gravatar?

**Comment by seb-vial** [comment]
I'm closing this issue as it's resolved. See #20 for this matter @gbschenkel
