### ISSUE TITLE
Validation failed: Invalid input in description

### ISSUE THREAD

**Issue by rytai** [Birssan/grav-plugin-about-me#2]
I'm getting this error whenever I'm editing description, using line brekas.

I can write a one liner and the default santa claus text showed up just fine.

That error comes up everytime I try and make even 2 lined description.

Is this a bug, or a feature?

OS:Win 7
Browser: Chrome

**Comment by seb-vial** [comment]
Yes, until now I used `<br>` to insert break lines.
Thanks for reminding me, I needed to correct that, I'll make a new release with a fix in a few !

**Comment by rytai** [comment]
Thanks a lot :) That was fast
