### ISSUE TITLE
After installing blank screen

### ISSUE THREAD

**Issue by deKoning** [Birssan/grav-plugin-about-me#28]
After I installed the plugin, I see a bank screen. Also the admin panel is not accessible anymore. My fix was to manually delete the plugin and the website worked again as before.

**Comment by f3nrir197x** [comment]
Same here, after installing the plugin, the page returns:
This page isn’t working
<site> is currently unable to handle this request.
HTTP ERROR 500

On the http log it shows up as:

[Mon Jun 05 19:19:42.143513 2023] [proxy_fcgi:error] [pid 123456:tid 123456789012345] [client x.y.z.a:0] AH01071: Got error 'PHP message: PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /path/to/the/website/public_html/user/plugins/aboutme/aboutme.php on line 71'

As per the suggestion error I added parenthesis in the line 71:
return ($a['position'] < $b['position']) ? -1 : (($a['position'] == $b['position']) ? 0 : 1);

It seems to be a problem with PHP version

**Comment by sapo33** [comment]
Same problem. PHP Version 8.2.8
Thanks for the fix.

**Comment by seb-vial** [comment]
A new release has been drafted and should soon be picked up by Grav.
