### ISSUE TITLE
Save Error from admin panel

### ISSUE THREAD

**Issue by jboeke** [Birssan/grav-plugin-about-me#6]
I tried installing aboutme via both gpm and through the admin ui. Either way as soon as I make any change (in this case my name) and press save, I get this error.

![screenshot2016-09-08 17-04-39](https://cloud.githubusercontent.com/assets/547704/18369995/966875ba-75e6-11e6-890e-4295df637d98.png)

**Comment by seb-vial** [comment]
What Grav version do you use ? There might have been some changes recently, I have to check that out, I'll get back to you.
Thanks for reporting this

**Comment by seb-vial** [comment]
Ok I fixed the issue, update to the latest version and it should be fine.
File upload has become a bit more complex but in a good way. I think the latest version of the admin plugin changed the way yaml files were merged (user config file for the plugin and the config file for the plugin itself). I changed the default config file of the plugin so it would match what is generated by Grav for the user config file.
