### ISSUE TITLE
Updating /localhost/config/plugins not /user/config/plugins

### ISSUE THREAD

**Issue by jeremycherfas** [Birssan/grav-plugin-about-me#7]
Hi. I've been trying to adjust some of my social information, and it seems that when the plugin saves, it is updating `/localhost/config/plugins/aboutme.yaml` rather than `/config/plugins/aboutme.yaml` so that my changes are not appearing on the production site.

**Comment by seb-vial** [comment]
Hello,

This behavior is managed by Grav not the plugin, there is no saving path hard coded in the plugin, except for avatar files destination (but it's relative path so it saves the files in the user config for this plugin ).

If you use the admin plugin, this should work out of the box (after fresh install for example).
If you installed the plugin manually, make sure your `aboutme.yaml` is correctly formatted ?

**Comment by jeremycherfas** [comment]
OK. I'll try a fresh install. Thanks.

**Comment by jeremycherfas** [comment]
OK, I think I managed in the end to get where I wanted, but I have to say, it wasn't easy. The instructions to copy `about.yaml` to `\localhost` did not work when I pushed from my local development environment to the production site. I had to copy the file manually to `\config\plugins`.

This may well be because I do not fully understand how to set up the evionment things, but anyway.

**Comment by seb-vial** [comment]
Well once you change the settings of a plugin from the admin interface, the yaml file is save in `user/config/plugins/name_of_the_plugin.yaml` in our case that would be `user/config/plugins/aboutme.yaml`

If you make a change on your local website you have to send this file on your production server. Or make the same change in your admin interface on your production site, which would change directly the right file on your production website
