### ISSUE TITLE
No content displayed

### ISSUE THREAD

**Issue by vincowl** [Birssan/grav-plugin-about-me#9]
While having installed about-me in grav 1.3.6, having activated it and inserted the `{% include 'partials/aboutme.html.twig' %}` line in a brand new page where twig processing is activated, no content is displayed. I only have a shadowed box with absolutely no content.
I tried to modify the aboutme.html.twig to display  `{{ about_name }}`, it seems that this variable is empty, while it had content correctly set in aboutme.php. Any idea ??

**Comment by seb-vial** [comment]
I haven't updated the plugin for a while now, I'll have to check if something changed in Grav which would explain this behavior.

**Comment by vincowl** [comment]
Thanks a lot ! Hope this won't imply too much work

**Comment by seb-vial** [comment]
It works fine on my side with a fresh install, here is what I did:
- Installed Grav with admin
- Installed AboutMe plugin
- Added a page using Default template with `{% include 'partials/aboutme.html.twig' %}` in the content and activated the twig processing

![image](https://user-images.githubusercontent.com/5689193/31598367-812f8b62-b24d-11e7-9d49-be867dd3a3aa.png)

Do you use the admin plugin or do you install and configure everything from the CLI ?
Do you have a `aboutme.yaml` file in your `user/config/plugins` folder that overrides the default configuration for the plugin ? If that's the case, make sure there is no formatting error in this file.

**Comment by vincowl** [comment]
I followed your steps on a brand new full installation from the CLI and it works perfectly (Apache2 / php7.0, grav 1.3.6 without admin plugin).

I still have the problem on my previous installation. It is based on [ahumaro/grav-php-nginx](https://github.com/ahumaro/Grav-PHP-Nginx) docker image (using nginx and php7.0). I made the whole installation / page creation using the admin plugin.

**Comment by vincowl** [comment]
I found what caused the problem : there must be a conflict with [ShortCodes Core plugin](https://github.com/getgrav/grav-plugin-shortcode-core). While deactivating it, AboutMe worked perfectly. I opened a new issue #10 to trace this since it is a new issue. This one may be closed.

**Comment by seb-vial** [comment]
Fixed in #10
